
package proxy;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.Action;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebService(name = "BanqueService", targetNamespace = "http://ws/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BanqueService {


    /**
     * 
     * @param amount
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "euroToXofConversion", targetNamespace = "http://ws/", className = "proxy.EuroToXofConversion")
    @ResponseWrapper(localName = "euroToXofConversionResponse", targetNamespace = "http://ws/", className = "proxy.EuroToXofConversionResponse")
    @Action(input = "http://ws/BanqueService/euroToXofConversionRequest", output = "http://ws/BanqueService/euroToXofConversionResponse")
    public double euroToXofConversion(
        @WebParam(name = "amount", targetNamespace = "")
        double amount);

    /**
     * 
     * @param code
     * @return
     *     returns proxy.Account
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAccount", targetNamespace = "http://ws/", className = "proxy.GetAccount")
    @ResponseWrapper(localName = "getAccountResponse", targetNamespace = "http://ws/", className = "proxy.GetAccountResponse")
    @Action(input = "http://ws/BanqueService/getAccountRequest", output = "http://ws/BanqueService/getAccountResponse")
    public Account getAccount(
        @WebParam(name = "code", targetNamespace = "")
        int code);

    /**
     * 
     * @return
     *     returns java.util.List<proxy.Account>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listAccount", targetNamespace = "http://ws/", className = "proxy.ListAccount")
    @ResponseWrapper(localName = "listAccountResponse", targetNamespace = "http://ws/", className = "proxy.ListAccountResponse")
    @Action(input = "http://ws/BanqueService/listAccountRequest", output = "http://ws/BanqueService/listAccountResponse")
    public List<Account> listAccount();

}
